name = "RangeTrees"
uuid = "e0f2e492-6013-4161-9c01-7f8b0fb75dfe"
authors = ["Iulia Dumitru <iuliadmtru@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
AbstractTrees = "0.4.5"
DataStructures = "0.18.20"
